# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Empty_table_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Empty_table(object):
    def setupUi(self, empty_table):
        empty_table.setObjectName("Empty_table")
        empty_table.setWindowModality(QtCore.Qt.NonModal)
        empty_table.resize(400, 140)
        empty_table.setMinimumSize(QtCore.QSize(400, 140))
        empty_table.setMaximumSize(QtCore.QSize(400, 140))
        self.label = QtWidgets.QLabel(empty_table)
        self.label.setGeometry(QtCore.QRect(20, 15, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(empty_table)
        self.pushButton.setGeometry(QtCore.QRect(150, 50, 231, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(empty_table)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 90, 221, 25))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(empty_table)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(empty_table)
        self.spinBox.setGeometry(QtCore.QRect(20, 50, 111, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(empty_table)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(empty_table)
        QtCore.QMetaObject.connectSlotsByName(empty_table)

    def retranslateUi(self, empty_table):
        _translate = QtCore.QCoreApplication.translate
        empty_table.setWindowTitle(_translate("Empty_table", "Empty Table"))
        self.label.setText(_translate("Empty_table", "Points amount"))
        self.pushButton.setText(_translate("Empty_table", "Create empty table"))
        self.pushButton_2.setText(_translate("Empty_table", "Instruction"))
        self.label_2.setText(_translate("Empty_table", "Empty Table"))
        self.label_3.setText(_translate("Empty_table", "Status"))
