from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_gce(object):
    def setupUi(self, gce):
        gce.setObjectName("gce")
        gce.resize(405, 230)
        gce.setMinimumSize(QtCore.QSize(405, 230))
        gce.setMaximumSize(QtCore.QSize(405, 230))
        self.tabWidget = QtWidgets.QTabWidget(gce)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 411, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.input = QtWidgets.QWidget()
        self.input.setObjectName("input")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.input)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 361, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.input)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 80, 125, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.input)
        self.label.setGeometry(QtCore.QRect(0, -1, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.input)
        self.label_2.setGeometry(QtCore.QRect(6, 39, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.input)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.tabWidget.addTab(self.input, "")
        self.output = QtWidgets.QWidget()
        self.output.setObjectName("output")
        self.label_5 = QtWidgets.QLabel(self.output)
        self.label_5.setGeometry(QtCore.QRect(6, 39, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.output)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 80, 125, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.output)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 120, 361, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.output)
        self.label_10.setGeometry(QtCore.QRect(0, -1, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.output)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 120, 361, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.tabWidget.addTab(self.output, "")

        self.retranslateUi(gce)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gce)

    def retranslateUi(self, gce):
        _translate = QtCore.QCoreApplication.translate
        gce.setWindowTitle(_translate("gce", "GeoCalc Extention"))
        self.pushButton.setText(_translate("gce", "Create txt file"))
        self.pushButton_2.setText(_translate("gce", "Create txt file"))
        self.pushButton_3.setText(_translate("gce", "Select File"))
        self.label.setText(_translate("gce", "Convert xlsx table to txt file for GeoCalc"))
        self.label_2.setText(_translate("gce", "Status"))
        self.label_3.setText(_translate("gce", "Arc Degrees"))
        self.label_4.setText(_translate("gce", "Meters XY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input), _translate("gce", "Input"))
        self.label_5.setText(_translate("gce", "Status"))
        self.pushButton_4.setText(_translate("gce", "Select File"))
        self.label_8.setText(_translate("gce", "Arc Degrees"))
        self.label_9.setText(_translate("gce", "Meters XY"))
        self.label_10.setText(_translate("gce", "Convert txt file to xlsx table"))
        self.pushButton_9.setText(_translate("gce", "Create xlsx table"))
        self.pushButton_10.setText(_translate("gce", "Create xlsx table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output), _translate("gce", "Output"))
